
import styles from "../styles/Home.module.css";
import Authentication from "../components/Authentication";
import Head from "next/head";
import {
    Box, Button,
    Heading,
    SimpleGrid,
    Table,
    TableCaption,
    TableContainer,
    Tbody,
    Td,
    Tfoot,
    Th,
    Thead,
    Tr,
    Text
} from "@chakra-ui/react";
import {faker} from '@faker-js/faker'
import {useEffect, useState} from "react";
export default function Browse(props) {
    const { isAuth, role } = props;
    const [data, setData] = useState([]);

    useEffect(() => {
        const data = new Array(100).fill().map(() => ({
            user: faker.internet.userName(),
            address: faker.finance.ethereumAddress(),
            score: faker.finance.amount()
        }));
        data.sort((a, b) => parseFloat(b.score) - parseFloat(a.score));

        setData(data);
    }, []);

    return(
        <div className={styles.container}>
            <Authentication isAuth={isAuth} />
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <Box padding={4}>
                    <Heading fontSize={{ base: '2xl', md: '3xl' }}>Leaderboard</Heading>
                    <Box overflowY="auto" maxHeight="500px" className={"max-w-4xl"}>
                        <Table variant="striped" colorScheme="teal">
                            <Thead position="sticky" top={0} bgColor="grey" zIndex={1}>
                                <Tr>
                                    <Th>Rank</Th>
                                    <Th>Name</Th>
                                    <Th>Address</Th>
                                </Tr>
                            </Thead>
                            <Tbody>
                                {data.map(({user,address,score},index) => (
                                    // eslint-disable-next-line react/jsx-key
                                    <Tr _hover={{ transform: "scale(1.05)" ,boxShadow: "base"}}
                                        transition="all 0.2s ease-out"
                                        overflow="clip">
                                        <Td>{index+1}</Td>
                                        <Td>{user}</Td>
                                        <Td>{address}</Td>
                                    </Tr>
                                ))}
                            </Tbody>
                        </Table>
                    </Box>
                </Box>
            </main>
        </div>
    )}