import { Box, SimpleGrid, Card, CardHeader, Heading, CardBody, Text, CardFooter, Button, Image, Checkbox } from "@chakra-ui/react";
import styles from "../styles/Home.module.css";
import Authentication from "../components/Authentication";
import Head from "next/head";
import woddsABI from "../ABI/wordsNFT.json";
import { ethers } from "ethers";
import { useWeb3Auth } from "../context/web3auth";
import Main from "../components/main";
import { useEffect, useState } from "react";
import Web3 from "web3";

export default function mintpage(props) {
    const { isAuth, role } = props;
    const { web3Auth,provider, isLoading } = useWeb3Auth()
    const [localProvider, setProvider] = useState(null);

    useEffect(() => {
        if (isLoading == false) {
            //  alert("GOT THERE");
        } else {
            setProvider(provider)
        }
    }, [isLoading, provider])

    async function mintNFT(_localProvider) {
        let woddsNFT = new web3.eth.Contract(woddsABI.address, woddsABI.abi, _localProvider)
        let tx = await woddsNFT.payToMint()
        await tx.wait(2)
        console.log(tx)
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Main></Main>

            <div className={styles.container}>
                <main className={styles.main}>
                    <Box className={"max-w-4xl hover:text-black min-w-600"}            >
                        <SimpleGrid spacing={10} row={1} columns={2}>
                            <Card _hover={{ transform: "scale(1.10)" }}
                                transition="all 0.2s ease-out"
                                display="inline-block"
                                overflow="hidden" >
                                <CardHeader>
                                    <Image borderRadius='10%' src={'https://media.tenor.com/lcuvD0zkFNMAAAAM/question-mark.gif'} boxsize='200px' alt='placeholder' />
                                    <Heading size='md' className={"my-4"}> Random Words NFT</Heading>
                                    <Text>Mint Words NFTs to compose a SongNFT</Text>

                                </CardHeader>

                            </Card>

                            <Button onClick={() => mintNFT(localProvider)}
                                style={{ marginTop: '140px' }} className={"max-w-4xl my-10"}> Mint Words</Button>

                        </SimpleGrid>
                    </Box>
                </main>
            </div>


        </div>
    );
}