import {Box, SimpleGrid, Card, CardHeader,Heading,CardBody,Text, CardFooter,Button, Image} from "@chakra-ui/react";
import styles from "../styles/Home.module.css";
import Authentication from "../components/Authentication";
import Head from "next/head";
import PixiCanvas from "../components/PixiCanvas";
export default function mintSong(props) {
    const { isAuth, role } = props;
    return(
        <div className={styles.container}>
            <Authentication isAuth={isAuth} />
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        <div className={styles.container}>
            <main className={styles.main}>
                <Box  className={"max-w-4xl max-h-screen hover:text-black"}>
                    <SimpleGrid spacing={10} row={1} columns={3}>
                        <Card >
                            <CardHeader>
                                <Image borderRadius='10%' src={'https://nationaltoday.com/wp-content/uploads/2022/08/4568128-min-1.jpg'} boxsize='200px' alt='placeholder'></Image>
                                <Heading size='md' className={"my-2"}> Customer dashboard</Heading>
                            </CardHeader>
                            <CardBody>
                                <Text>View a summary of all your customers over the last month.</Text>
                            </CardBody>
                            <CardFooter>
                                <Button>View here</Button>
                            </CardFooter>
                        </Card>
                        <Card>
                            <CardHeader>
                                <Image borderRadius='10%' src={'https://upload.wikimedia.org/wikipedia/en/b/b0/Yoasobi_-_Idol.png'} boxsize='200px' alt='placeholder'></Image>
                                <Heading size='md' className={"my-2"}> Customer dashboard</Heading>
                            </CardHeader>
                            <CardBody>
                                <Text>View a summary of all your customers over the last month.</Text>
                            </CardBody>
                            <CardFooter>
                                <Button>View here</Button>
                            </CardFooter>
                        </Card>
                        <Card>
                            <CardHeader>
                                <Image borderRadius='10%' src={'https://upload.wikimedia.org/wikipedia/en/a/a6/Fifty_Fifty_-_The_Beginning_Cupid.png'} boxsize='200px' alt='placeholder'></Image>
                                <Heading size='md' className={"my-2"}> Customer dashboard</Heading>
                            </CardHeader>
                            <CardBody>
                                <Text>View a summary of all your customers over the last month.</Text>
                            </CardBody>
                            <CardFooter>
                                <Button>View here</Button>
                            </CardFooter>
                        </Card>
                    </SimpleGrid>
                </Box>
                <Button className={"max-w-4xl my-10"}> Mint Song</Button>
            </main>
        </div>


        </div>
    );
}