import {Box, SimpleGrid, Card, CardHeader,Heading,CardBody,Text, CardFooter,Button, Image, Checkbox} from "@chakra-ui/react";
import styles from "../styles/Home.module.css";
import Authentication from "../components/Authentication";
import Head from "next/head";
export default function mintSong(props) {
    const { isAuth, role } = props;
    return(
        <div className={styles.container}>
            <Authentication isAuth={isAuth} />
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        <div className={styles.container}>
            <main className={styles.main}>
                <Box  className={"max-w-4xl hover:text-black min-w-600"}            >
                    <SimpleGrid spacing={10} row={1} columns={3}>
                        <Card _hover={{ transform: "scale(1.10)" }}
                              transition="all 0.2s ease-out"
                              display="inline-block"
                              overflow="hidden" >
                            <CardHeader>
                                    <Image borderRadius='10%' src={'https://nationaltoday.com/wp-content/uploads/2022/08/4568128-min-1.jpg'} boxsize='200px' alt='placeholder'/>
                                <Heading size='md' className={"my-2"}> Customer dashboard</Heading>
                            </CardHeader>
                            <CardBody>
                                <Text>View a summary of all your customers over the last month.</Text>
                            </CardBody>
                            <CardFooter>
                                <Checkbox size={"lg"}>Select</Checkbox>
                            </CardFooter>
                        </Card>
                        <Card _hover={{ transform: "scale(1.10)" ,boxShadow: "base"}}
                                    transition="all 0.2s ease-out"
                                    display="inline-block"
                                    overflow="hidden"
                        >
                            <CardHeader>
                                <Image borderRadius='10%' src={'https://upload.wikimedia.org/wikipedia/en/b/b0/Yoasobi_-_Idol.png'} boxsize='200px' alt='placeholder'></Image>
                                <Heading size='md' classNameΩ={"my-2"}> Customer dashboard</Heading>
                            </CardHeader>
                            <CardBody>
                                <Text>View a summary of all your customers over the last month.</Text>
                            </CardBody>
                            <CardFooter>
                                <Checkbox size={"lg"}>Select</Checkbox>
                            </CardFooter>
                        </Card>
                        <Card _hover={{ transform: "scale(1.10)" }}
                              transition="all 0.2s ease-out"
                              display="inline-block"
                              overflow="hidden" >
                            <CardHeader>
                                <Image borderRadius='10%' src={'https://upload.wikimedia.org/wikipedia/en/a/a6/Fifty_Fifty_-_The_Beginning_Cupid.png'} boxsize='200px' alt='placeholder'></Image>
                                <Heading size='md' className={"my-2"}> Customer dashboard</Heading>
                            </CardHeader>
                            <CardBody>
                                <Text>View a summary of all your customers over the last month.</Text>
                            </CardBody>
                            <CardFooter>
                                <Checkbox size={"lg"}>Select</Checkbox>
                            </CardFooter>
                        </Card>
                    </SimpleGrid>
                </Box>
                <Button className={"max-w-4xl my-10"}> Mint Song</Button>
            </main>
        </div>


        </div>
    );
}